### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PixyBoi69** [NgLamVN/LMAO#1]
Freezing 🥶 Stick
Rotate Stick
KnockBack Stick
Anvil Drop Stick (commands are slow to type)
Sound Spam Cmd or Stick
MakeItGreedy Stick (It's spawn ton of rare item that player want to pickup but HE CAN'T)

I'll suggest more if I will get any idea

**Comment by NgLam2911** [comment]
> Freezing 🥶 Stick Rotate Stick KnockBack Stick Anvil Drop Stick (commands are slow to type) Sound Spam Cmd or Stick MakeItGreedy Stick (It's spawn ton of rare item that player want to pickup but HE CAN'T)
> 
> I'll suggest more if I will get any idea

So actually its a troll tool ...
for Greedy troll, can other player pickup the rare item ?

Thanks for you suggestion :>

**Comment by NgLam2911** [comment]
Moved to #2
