### ISSUE TITLE
crashes when a player joins

### ISSUE THREAD

**Issue by logannn61** [NgLamVN/LMAO#13]
https://crash.pmmp.io/view/6669481

**Comment by NgLam2911** [comment]
This is the rare problem caused by the `Commando` library... so... I will be working on a patch soon...

**Comment by NgLam2911** [comment]
Please check lastest build of this plugin on poggit, let me know if this issues have been fixed. Thanks ~~

**Comment by logannn61** [comment]
nope it still crashes

**Comment by logannn61** [comment]
11.05 04:12:28 [Server] CRITICAL TypeError: "pocketmine\\command\\SimpleCommandMap::getCommand(): Argument #1 ($name) must be of type string, int given, called in phar:///plugins/LMAO_dev-39.phar/src/NgLam2911/lmao/libs/CortexPE/Commando/PacketHooker.php on line 69" (EXCEPTION) in "pmsrc/src/command/SimpleCommandMap" at line 241
11.05 04:12:28 [Server] INFO --- Stack trace ---
11.05 04:12:28 [Server] INFO #0 plugins/LMAO_dev-39.phar/src/NgLam2911/lmao/libs/CortexPE/Commando/PacketHooker(69): pocketmine\\command\\SimpleCommandMap->getCommand(integer 1812)
11.05 04:12:28 [Server] INFO #1 plugins/LMAO_dev-39.phar/src/NgLam2911/lmao/libs/CortexPE/Commando/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(94): NgLam2911\\lmao\\libs\\CortexPE\\Commando\\PacketHooker::NgLam2911\\lmao\\libs\\CortexPE\\Commando\\{closure}(object pocketmine\\network\\mcpe\\protocol\\AvailableCommandsPacket#1052001, object pocketmine\\network\\mcpe\\NetworkSession#1041207)
11.05 04:12:28 [Server] INFO #2 pmsrc/src/event/RegisteredListener(75): NgLam2911\\lmao\\libs\\CortexPE\\Commando\\libs\\muqsit\\simplepackethandler\\interceptor\\PacketInterceptorListener->NgLam2911\\lmao\\libs\\CortexPE\\Commando\\libs\\muqsit\\simplepackethandler\\interceptor\\{closure}(object pocketmine\\event\\server\\DataPacketSendEvent#1052003)
11.05 04:12:28 [Server] INFO #3 pmsrc/src/event/Event(62): pocketmine\\event\\RegisteredListener->callEvent(object pocketmine\\event\\server\\DataPacketSendEvent#1052003)
11.05 04:12:28 [Server] INFO #4 pmsrc/src/network/mcpe/NetworkSession(416): pocketmine\\event\\Event->call()
11.05 04:12:28 [Server] INFO #5 pmsrc/src/network/mcpe/NetworkSession(879): pocketmine\\network\\mcpe\\NetworkSession->sendDataPacket(object pocketmine\\network\\mcpe\\protocol\\AvailableCommandsPacket#1052001)
11.05 04:12:28 [Server] INFO #6 pmsrc/src/network/mcpe/handler/PreSpawnPacketHandler(114): pocketmine\\network\\mcpe\\NetworkSession->syncAvailableCommands()
11.05 04:12:28 [Server] INFO #7 pmsrc/src/network/mcpe/NetworkSession(319): pocketmine\\network\\mcpe\\handler\\PreSpawnPacketHandler->setUp()
11.05 04:12:28 [Server] INFO #8 pmsrc/src/network/mcpe/NetworkSession(697): pocketmine\\network\\mcpe\\NetworkSession->setHandler(object pocketmine\\network\\mcpe\\handler\\PreSpawnPacketHandler#1047729)
11.05 04:12:28 [Server] INFO #9 pmsrc/src/network/mcpe/NetworkSession(270): pocketmine\\network\\mcpe\\NetworkSession->beginSpawnSequence()
11.05 04:12:28 [Server] INFO #10 pmsrc/src/promise/Promise(45): pocketmine\\network\\mcpe\\NetworkSession->onPlayerCreated(object ipad54\\netherblocks\\player\\Player#1040252)
11.05 04:12:28 [Server] INFO #11 pmsrc/src/network/mcpe/NetworkSession(234): pocketmine\\promise\\Promise->onCompletion(object Closure#1040962, object Closure#1040966)
11.05 04:12:28 [Server] INFO #12 pmsrc/src/network/mcpe/NetworkSession(692): pocketmine\\network\\mcpe\\NetworkSession->createPlayer()
11.05 04:12:28 [Server] INFO #13 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\\network\\mcpe\\NetworkSession->pocketmine\\network\\mcpe\\{closure}()
11.05 04:12:28 [Server] INFO #14 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\\network\\mcpe\\handler\\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\\network\\mcpe\\protocol\\ResourcePackClientResponsePacket#1040967)
11.05 04:12:28 [Server] INFO #15 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\\network\\mcpe\\protocol\\ResourcePackClientResponsePacket->handle(object pocketmine\\network\\mcpe\\handler\\ResourcePacksPacketHandler#1040113)
11.05 04:12:28 [Server] INFO #16 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\\network\\mcpe\\NetworkSession->handleDataPacket(object pocketmine\\network\\mcpe\\protocol\\ResourcePackClientResponsePacket#1040967, string[4] ....)
11.05 04:12:28 [Server] INFO #17 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\\network\\mcpe\\NetworkSession->handleEncoded(string[7] c.`a`..)
11.05 04:12:28 [Server] INFO #18 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\\network\\mcpe\\raklib\\RakLibInterface->onPacketReceive(integer 0, string[16] ...:p...).B...2K)
11.05 04:12:28 [Server] INFO #19 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\\server\\ipc\\RakLibToUserThreadMessageReceiver->handle(object pocketmine\\network\\mcpe\\raklib\\RakLibInterface#1043343)
11.05 04:12:28 [Server] INFO #20 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\\network\\mcpe\\raklib\\RakLibInterface->pocketmine\\network\\mcpe\\raklib\\{closure}()
11.05 04:12:28 [Server] INFO #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\\snooze\\SleeperHandler->processNotifications()
11.05 04:12:28 [Server] INFO #22 pmsrc/src/Server(1661): pocketmine\\snooze\\SleeperHandler->sleepUntil(double 1652235148.7301)
11.05 04:12:28 [Server] INFO #23 pmsrc/src/Server(1047): pocketmine\\Server->tickProcessor()
11.05 04:12:28 [Server] INFO #24 pmsrc/src/PocketMine(304): pocketmine\\Server->__construct(object BaseClassLoader#2, object pocketmine\\utils\\MainLogger#3, string[48] /, string[56] /plugins/)
11.05 04:12:28 [Server] INFO #25 pmsrc/src/PocketMine(327): pocketmine\\server()
11.05 04:12:28 [Server] INFO #26 pmsrc(11): require(string[92] phar:///PocketMine-MP.phar/src/Po)
11.05 04:12:28 [Server] INFO --- End of exception information ---
11.05 04:12:28 [Server] EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
11.05 04:12:28 [PebbleHost] Logannn61 ran command Message of the Day
11.05 04:12:28 [Server] EMERGENCY Please upload the "/crashdumps/Wed_May_11-02.12.28-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
11.05 04:12:29 [Server] EMERGENCY The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/6681888 or use the ID #6681888.

**Comment by NgLam2911** [comment]
Try https://poggit.pmmp.io/r/174978/LMAO_dev-39.phar

**Comment by logannn61** [comment]
> Try https://poggit.pmmp.io/r/174978/LMAO_dev-39.phar

Hi, that is the build I am using

**Comment by NgLam2911** [comment]
> Author

Basically, the plugin doesn't cause the server to crash. This issue is related to the `Commando` library, so it's really hard to detect the problem. On a clean server, I can't currently reproduce this issue.

**Comment by logannn61** [comment]
is there anything i can do then

**Comment by NgLam2911** [comment]
> is there anything i can do then

Maybe not... or try removing some plugins. I don't know what is causing this issue.
