### ISSUE TITLE
HELP!!

### ISSUE THREAD

**Issue by DevGrishin** [NgLamVN/LMAO#16]
The page doesnt specify how to use the commands, its really not a problem for most of them except for the spin command. I dont really get how to set the speed and amount of times people spin pls help

**Comment by NgLam2911** [comment]
> The page doesnt specify how to use the commands, its really not a problem for most of them except for the spin command. I dont really get how to set the speed and amount of times people spin pls help

There are 3 argument for this command:
* Speed: How fast when spining a player... Higher speed = faster spin. [Default is 1]
* Times: How much times player spin around 360 degree [Default is 1]
* Direction: Just left or right (You can test it in game and see what's different) [Default is left]

Every argument in here is optional.

Thanks !
