### ISSUE TITLE
Pumpkin head Troll

### ISSUE THREAD

**Issue by MrBlasyMSK** [NgLamVN/LMAO#6]
A mythical tool is missing, what it does is to put a pumpkin head on the player.

Points to keep in mind not to ruin the user experience:
1 - If the player has a helmet on his head, move it to his inventory so as not to remove it with the pumpkin (I say this in case he is enchanted and it has cost him a lot).
2 - If he has no space in his inventory, drop the helmet he is wearing and put the pumpkin on it.
3 -

https://user-images.githubusercontent.com/85447029/162554219-19c6a3a8-3265-4689-b4c1-4202d5d4756e.mp4

**Comment by NgLam2911** [comment]
Currently I don't know what happens if i don't make a undo action system but seem funny
